# Generated by Django 3.2.7 on 2021-11-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_id', models.CharField(max_length=60)),
                ('crypto_name', models.CharField(max_length=60)),
                ('operation', models.CharField(max_length=4)),
                ('unit_price', models.FloatField()),
                ('unit', models.CharField(default='usd', max_length=10)),
                ('quantity', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
